### ISSUE TITLE
the current version of the source code sends no test data

### ISSUE THREAD

**Issue by dmedine** [RhythmsOfRelating/HybridHarmony#10]
After a fresh pull, I can see outlets but no data is sent. Attempting to break into https://github.com/RhythmsOfRelating/HybridHarmony/blob/master/src/analysis/correlation_perFreq.py#L107 does not work (the code is never hit) and indeed no data is sent. This may have resulted from the restructure of the directories.

**Comment by phoebsc** [comment]
I accidentally deleted a function last time cleaning the code. Should be working now.

**Comment by dmedine** [comment]
Indeed. This was fixed in https://github.com/RhythmsOfRelating/HybridHarmony/commit/a94120a9f8c5e28e44d572e9042d522091a6e94e
