### ISSUE TITLE
Why does the Correlation object need to be created over and over again?

### ISSUE THREAD

**Issue by dmedine** [RhythmsOfRelating/HybridHarmony#12]
The rather massive Correlation object gets re-created with the same information in a tight loop https://github.com/RhythmsOfRelating/HybridHarmony/blob/master/src/analysis/analysis.py#L133

This may have been my doing, but if not, is there a reason that this isn't created only once? I for one, would like to create it when the analysis object is initialized. Then run (https://github.com/RhythmsOfRelating/HybridHarmony/blob/master/src/analysis/correlation_perFreq.py#L85) should be a loop on its own thread that waits for new data to process.

**Comment by phoebsc** [comment]
It was indeed modified from before. I have moved as much initialization to "analysis" as possible: Now the [analysis](https://github.com/RhythmsOfRelating/HybridHarmony/blob/6232c6fafa5bb50261cea449f3c3e0bfb92135ba/src/analysis/analysis.py#L62) object sets up filtering coefficients, outlets, hanning window, etc. the [setup](https://github.com/RhythmsOfRelating/HybridHarmony/blob/6232c6fafa5bb50261cea449f3c3e0bfb92135ba/src/analysis/correlation_perFreq.py#L79) in "correlation" doesn't really do anything, and the entire "correlation" object only performs the necessary steps for computation. 

Is the initialization itself (which only passes on parameters) costly? What do you suggest?

**Comment by phoebsc** [comment]
edit: trying to move the correlation object instantiation to the analysis initialization

**Comment by phoebsc** [comment]
declaration of the correlation object is now in analysis initialization (devel-PC branch)
https://github.com/RhythmsOfRelating/HybridHarmony/blob/9af544c72825706c5a926f263f2f3a9bff4fdb90/src/analysis/analysis.py#L71

**Comment by dmedine** [comment]
Sorry, I didn't make this clear. I already fixed this up. 

https://github.com/RhythmsOfRelating/HybridHarmony/pull/13

**Comment by dmedine** [comment]
The re-creation of the correlation object comes at the cost of a fair amount of memory allocation. This is pretty costly from a performance point of view. In general I am not super happy with the performance of the whole system. I am trying to figure out ways to optimize things.

**Comment by phoebsc** [comment]
That makes sense! Thank you so much! On optimization: I'm wondering
1) are there ways to optimize the matrix computation in correlation? 
2) is it helpful if we make analysis a QThread instead of a python built-in thread? That way, we can implement real-time normalization using signals/slots (e.g. analysis object reads input from main_GUI whenever the slider moves).
