### ISSUE TITLE
Application crashes when 'stop analysis' is pressed after stream input disappears

### ISSUE THREAD

**Issue by dmedine** [RhythmsOfRelating/HybridHarmony#20]
Steps to recreate:

1. Run the application, 
2. select Tools->play a random sample for testing
3. press 1. Load LSL streams
4. check display connectivity values
5. press 2. start analysis
6. select Tools->stop generating
7. press stop analysis

result: application hangs and then crashes

I can stop this behavior by not signalling to kill the Display thread in `fun_stop`. Commenting out the signal emitter in the display object (this line: https://github.com/RhythmsOfRelating/HybridHarmony/blob/master/src/main_GUI.py#L1071) seems to do the trick. 

@phoebsc, unless there is a need to emit this signal that I am not seeing, I think we can make this change.

**Comment by phoebsc** [comment]
Thanks for spotting the issue! My only concern is whether restarting the analysis ("start"-->"stop"-->"start") would work after you make this change.

**Comment by dmedine** [comment]
Yes (surprisingly)! At least on Windows, it seems to be fine.
