### ISSUE TITLE
TODO List for PC from discussions with DM

### ISSUE THREAD

**Issue by dmedine** [RhythmsOfRelating/HybridHarmony#6]
TODO List (if I remember correctly)
1. improved documentation (with SH)
2. start documentation for walk through (belongs in RhythmsOfRelating)
3. add icon to upper left hand corner of app
4. fix up menu:
    1. start items with Caps
    2. remove function
    3. add About with version number, links to docs (pending), and license
5. anything else?

**Comment by phoebsc** [comment]
for 4. fix up menu, should the menu bar contain 'Tools', 'Help' and 'About', where 'Help' and 'About' don't have drop down options?
btw, can you make the super repo public?

**Comment by dmedine** [comment]
Yes. Tools Help and About sounds right. And, I will make the super repo public. You should be able to do that too. If not, I will try to upgrade your permissions.

**Comment by phoebsc** [comment]
I pushed these changes and created the wiki pages: https://github.com/RhythmsOfRelating/HybridHarmony/wiki
